media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: 'posts'
    view:
      fields:
        - title
        - published
        - date
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: Cover
        label: CoverImage
        list: true
        options:
          path: "media/"  # Ensure quotes for string values
          extensions: [ jpg, jpeg, png ]
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
